# Generated by Django 3.0.6 on 2021-04-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_upload_is_paired'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_exome',
            field=models.BooleanField(default=False),
        ),
    ]
