# Generated by Django 3.0.6 on 2021-06-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20210427_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='patient_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
