# Generated by Django 3.0.6 on 2021-10-31 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploader', '0006_upload_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=127, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unknown', 'unknown')], max_length=31)),
                ('date_of_birth', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='upload',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='PhenotypeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded', models.BooleanField(default=False)),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ontology_class', to='uploader.OntologyClass')),
            ],
        ),
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padigree_brother', to='uploader.Patient')),
                ('father', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padigree_father', to='uploader.Patient')),
                ('mother', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padigree_mother', to='uploader.Patient')),
                ('sister', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='padigree_sister', to='uploader.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='pedigree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='uploader.Pedigree'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phentypes',
            field=models.ManyToManyField(to='uploader.PhenotypeFeature'),
        ),
        migrations.AddField(
            model_name='upload',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upload_patient', to='uploader.Patient'),
        ),
    ]
