# Generated by Django 3.0.6 on 2021-11-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_auto_20211031_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pedigree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='uploader.Pedigree'),
        ),
    ]
