# Generated by Django 3.0.6 on 2021-11-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_auto_20211102_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='identifier',
            field=models.CharField(max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='mrn',
            field=models.CharField(max_length=63, null=True, unique=True),
        ),
    ]
