# Generated by Django 3.0.6 on 2021-11-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_auto_20211102_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phentypes',
            new_name='phenotypes',
        ),
    ]
