# Generated by Django 3.0.6 on 2021-11-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_auto_20211103_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='ontologyclass',
            name='uri',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
