# Generated by Django 3.0.6 on 2021-11-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_ontologyclass_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='assembly',
            field=models.CharField(choices=[('GRCh38', 'GRCh38'), ('GRCh37', 'GRCh37')], default='GRCh38', max_length=15),
        ),
        migrations.AddField(
            model_name='upload',
            name='bed_file_location',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='bed_filename',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='father_assembly',
            field=models.CharField(choices=[('GRCh38', 'GRCh38'), ('GRCh37', 'GRCh37')], default='GRCh38', max_length=15),
        ),
        migrations.AddField(
            model_name='upload',
            name='father_bed_file_location',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='father_bed_filename',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='father_sequence_file_location1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='father_sequence_file_location2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='father_sequence_filename1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='father_sequence_filename2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mother_assembly',
            field=models.CharField(choices=[('GRCh38', 'GRCh38'), ('GRCh37', 'GRCh37')], default='GRCh38', max_length=15),
        ),
        migrations.AddField(
            model_name='upload',
            name='mother_bed_file_location',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mother_bed_filename',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mother_sequence_file_location1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mother_sequence_file_location2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mother_sequence_filename1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='mother_sequence_filename2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sequence_file_location1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sequence_file_location2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sequence_filename1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sequence_filename2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sibling_assembly',
            field=models.CharField(choices=[('GRCh38', 'GRCh38'), ('GRCh37', 'GRCh37')], default='GRCh38', max_length=15),
        ),
        migrations.AddField(
            model_name='upload',
            name='sibling_bed_file_location',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sibling_bed_filename',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sibling_sequence_file_location1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sibling_sequence_file_location2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sibling_sequence_filename1',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='sibling_sequence_filename2',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
    ]
