# Generated by Django 3.0.6 on 2021-12-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0012_auto_20211117_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='is_exome_father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_exome_mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_exome_sibling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_paired_father',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_paired_mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='upload',
            name='is_paired_sibling',
            field=models.BooleanField(default=False),
        ),
    ]
