# Generated by Django 3.0.6 on 2021-12-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0013_auto_20211201_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='upload',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('draft', 'draft'), ('validated', 'validated'), ('error', 'error'), ('uploaded', 'uploaded')], default='submitted', max_length=15),
        ),
    ]
